# frpc.ini
[common]
server_addr = powerai.cc
server_port = 7880

[ssh 36000]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 36000

[range:llm]
type = tcp
local_ip = 127.0.0.1
local_port = 8001-8011
remote_port = 38001-38011

[range:ui]
type = tcp
local_ip = 127.0.0.1
local_port = 7860-7879
remote_port = 37860-37879

[rdp 33390]
type = tcp
local_ip = 127.0.0.1
local_port = 3390
remote_port = 33390